# Generated by Django 2.1.5 on 2019-01-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0002_auto_20190111_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='duration',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True, verbose_name='duration'),
        ),
        migrations.AlterField(
            model_name='action',
            name='duration_unit',
            field=models.CharField(blank=True, choices=[('w', 'week'), ('d', 'day'), ('h', 'hour'), ('m', 'minute')], db_index=True, max_length=1, null=True, verbose_name='duration unit'),
        ),
        migrations.AlterField(
            model_name='action',
            name='estimate',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True, verbose_name='estimate'),
        ),
        migrations.AlterField(
            model_name='action',
            name='estimate_unit',
            field=models.CharField(blank=True, choices=[('w', 'week'), ('d', 'day'), ('h', 'hour'), ('m', 'minute')], db_index=True, max_length=1, null=True, verbose_name='estimate unit'),
        ),
    ]
