# Generated by Django 2.1.5 on 2019-01-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0003_auto_20190111_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='dependency_set',
            field=models.ManyToManyField(blank=True, related_name='subordinate_set', to='action.Action', verbose_name='dependencies'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='location'),
        ),
    ]
