# Generated by Django 2.1.5 on 2019-01-11 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0004_auto_20190111_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='date')),
                ('content', models.TextField(db_index=True, verbose_name='content')),
            ],
            options={
                'verbose_name': 'log',
                'verbose_name_plural': 'log book',
                'ordering': ('date', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(db_index=True, verbose_name='number')),
                ('content', models.TextField(db_index=True, verbose_name='content')),
            ],
            options={
                'verbose_name': 'note',
                'verbose_name_plural': 'notes',
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_on', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='planned on')),
                ('content', models.TextField(db_index=True, verbose_name='content')),
            ],
            options={
                'verbose_name': 'step',
                'verbose_name_plural': 'steps',
                'ordering': ('planned_on', 'id'),
            },
        ),
        migrations.AlterField(
            model_name='action',
            name='duration_unit',
            field=models.CharField(blank=True, choices=[('w', 'week(s)'), ('d', 'day(s)'), ('h', 'hour(s)'), ('m', 'minute(s)')], db_index=True, max_length=1, null=True, verbose_name='duration unit'),
        ),
        migrations.AlterField(
            model_name='action',
            name='estimate_unit',
            field=models.CharField(blank=True, choices=[('w', 'week(s)'), ('d', 'day(s)'), ('h', 'hour(s)'), ('m', 'minute(s)')], db_index=True, max_length=1, null=True, verbose_name='estimate unit'),
        ),
        migrations.AddField(
            model_name='step',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_set', to='action.Action', verbose_name='action'),
        ),
        migrations.AddField(
            model_name='note',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_set', to='action.Action', verbose_name='action'),
        ),
        migrations.AddField(
            model_name='log',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_set', to='action.Action', verbose_name='action'),
        ),
        migrations.AlterIndexTogether(
            name='note',
            index_together={('action', 'number')},
        ),
    ]
