# Generated by Django 2.1.5 on 2019-01-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0005_auto_20190111_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='number',
            field=models.PositiveSmallIntegerField(db_index=True, default=1, verbose_name='number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='step',
            name='number',
            field=models.PositiveSmallIntegerField(db_index=True, default=1, verbose_name='number'),
            preserve_default=False,
        ),
    ]
