# Generated by Django 2.1.5 on 2019-01-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0006_auto_20190111_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='departure_time',
            field=models.TimeField(blank=True, db_index=True, null=True, verbose_name='time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='location'),
        ),
    ]
